"""Full pipeline test — AI + LMS + Document generation."""

import asyncio
import logging
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    stream=sys.stderr,
)


async def main():
    from dotenv import load_dotenv
    load_dotenv()

    print("=" * 60)
    print("FULL PIPELINE TEST")
    print("=" * 60)

    # ── 1. Test AI client (Gemini) ──
    print("\n[1/4] Testing Gemini AI client...")
    from app.ai.client import LLMClient
    client = LLMClient()
    try:
        result = client.generate(
            system_prompt="You are a helpful assistant.",
            user_prompt="Say 'Hello from Gemini!' in exactly those words.",
            max_tokens=50,
            temperature=0.1,
        )
        print(f"  Result: {result.strip()}")
        print("  ✅ AI client works")
    except Exception as e:
        print(f"  ❌ AI client error: {e}")

    # ── 2. Test LMS assignment listing ──
    print("\n[2/4] Testing LMS assignment listing...")
    from app.lms.browser import get_browser, close_browser
    from app.lms.auth import login
    from app.lms.assignments import list_assignments

    browser = await get_browser()
    page = await browser.start(headless=False)
    try:
        await login()
        assignments = await list_assignments()
        print(f"  Found {len(assignments)} assignments:")
        for a in assignments[:5]:
            print(f"    • [{a['id']}] {a['title']}")
        if len(assignments) > 5:
            print(f"    ... and {len(assignments)-5} more")

        # ── 3. Test getting first assignment details ──
        if assignments:
            print(f"\n[3/4] Getting details for assignment {assignments[0]['id']}...")
            from app.lms.assignments import get_assignment
            details = await get_assignment(assignments[0]["id"])
            print(f"  Title: {details.get('title', 'N/A')}")
            print(f"  Course: {details.get('course', 'N/A')}")
            print(f"  Due: {details.get('due_date', 'N/A')[:50]}")
            print(f"  Attachments: {len(details.get('attachments', []))}")
            print("  ✅ Assignment details fetched")

    except Exception as e:
        print(f"  ❌ LMS error: {e}")
        import traceback
        traceback.print_exc()
    finally:
        await close_browser()

    # ── 4. Test document generation ──
    print("\n[4/4] Testing document generation...")
    from app.documents.generator import generate_docx
    try:
        path = generate_docx(
            "test-001",
            "Test Assignment",
            "Test Course",
            "# Test Solution\n\nThis is a **test** solution generated by the pipeline.",
        )
        print(f"  Generated: {path}")
        print("  ✅ Document generation works")
    except Exception as e:
        print(f"  ❌ Document generation error: {e}")

    print("\n" + "=" * 60)
    print("TEST COMPLETE")
    print("=" * 60)


asyncio.run(main())
