"""Document templates and student info for generated submissions."""

from config.settings import STUDENT_NAME, STUDENT_REG_NO, STUDENT_DEPT, STUDENT_YEAR


def get_student_info() -> dict[str, str]:
    """Return student information for document headers."""
    return {
        "name": STUDENT_NAME or "Student Name",
        "reg_no": STUDENT_REG_NO or "Registration Number",
        "dept": STUDENT_DEPT or "Department",
        "year": STUDENT_YEAR or "Year",
    }


def render_markdown_template(
    title: str,
    subject: str,
    solution_markdown: str,
) -> str:
    """Wrap the solution markdown in a full document template."""
    info = get_student_info()

    template = f"""---
title: {title}
subject: {subject}
student: {info['name']}
reg_no: {info['reg_no']}
date: {{date}}
---

# {title}

**Subject**: {subject}  
**Student**: {info['name']} ({info['reg_no']})  
**Department**: {info['dept']}  
**Date**: {{date}}

---

{solution_markdown}

---

*Generated by AI-Powered LMS Assistant*
"""
    return template
